version: '3.1'

services:

  postgres_kanban_quarkus:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanbanboard
      POSTGRES_PASSWORD: kanbanboard
