version: '3.7'

services:

  postgres:
    container_name: postgres_kanbanboard
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanbanboard
      POSTGRES_PASSWORD: kanbanboard

  jaeger:
    container_name: jaeger_kanbanboard
    image: jaegertracing/all-in-one:1.18
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus:
    container_name: prometheus_kanbanboard
    image: prom/prometheus:v2.19.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"

  grafana:
    container_name: grafana_kanbanboard
    image: grafana/grafana:7.1.0
    network_mode: "host"

  # se ocorrer [1]: max virtual memory areas vm.max_map_count [65530] is too low,
  # increase to at least [262144]
  # sudo sysctl -w vm.max_map_count=262144
  elastic:
    container_name: elasticsearch_kanbanboard
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    network_mode: "host"
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    container_name: kibana_kanbanboard
    image: docker.elastic.co/kibana/kibana:7.8.0
    network_mode: "host"
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200

  logstash:
    container_name: logstash_kanbanboard
    image: docker.elastic.co/logstash/logstash-oss:7.8.0
    volumes:
      - ./pipelines:/usr/share/logstash/pipeline
    network_mode: "host"
    depends_on:
      - elastic
