version: '3.7'

services:

  postgres:
    container_name: postgres_kanbanboard
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanbanboard
      POSTGRES_PASSWORD: kanbanboard

  jaeger:
    container_name: jaeger_kanbanboard
    image: jaegertracing/all-in-one:1.18
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus:
    container_name: prometheus_kanbanboard
    image: prom/prometheus:v2.19.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"

  grafana:
    container_name: grafana_kanbanboard
    image: grafana/grafana:7.1.0
    network_mode: "host"
